//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public int ID_PERSONAS { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string NIF { get; set; }
        public string Dirección { get; set; }
        public string Ciudad { get; set; }
        public string Estado_Civil { get; set; }
        public string Sexo { get; set; }
        public Nullable<int> Código_Postal { get; set; }
        public string Provincia { get; set; }

        public override string ToString()
        {
            return "nombre: " + Nombre + "\napellidos: " + Apellidos + "\nNIF: " + NIF + "\nDireccion: " + Dirección + "\nciudad: " + Ciudad + "\nestado civil: " + Estado_Civil + "\nsexo: " + Sexo + "\ncodigo postal: " + Código_Postal.ToString() + "\nprovincia: " + Provincia;
        }
    }
}
