//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coche
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coche()
        {
            this.operaciones = new HashSet<operaciones>();
        }
    
        public int id_coche { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> puertas { get; set; }
        public string color { get; set; }
        public Nullable<int> kilometraje { get; set; }
        public string tipo { get; set; }
        public Nullable<int> garantia { get; set; }
        public Nullable<int> stock { get; set; }
        public string foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<operaciones> operaciones { get; set; }
    }
}
