//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CutreCocheEntities : DbContext
    {
        public CutreCocheEntities()
            : base("name=CutreCocheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<coche> coche { get; set; }
        public virtual DbSet<operaciones> operaciones { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<tipo_operacion> tipo_operacion { get; set; }
        public virtual DbSet<tipo_persona> tipo_persona { get; set; }
    }
}
